### ISSUE TITLE
`no_stocks` is undefined

### ISSUE THREAD

**Issue by yuta-hitomi** [midas-research/fast-eacl#1]
I ran the your training script, but got the following error.

```
python train.py 
Traceback (most recent call last):
  File "train.py", line 210, in <module>
    model = FAST().to('cuda')
  File "/home/ubuntu/fast-eacl/model.py", line 74, in __init__
    self.text_lstm = [nn.LSTM(768,64) for _ in range(no_stocks)]
NameError: name 'no_stocks' is not defined
```
It seems that `no_stocks` is not defined in `train.py`. What does `no_stocks` represent?

**Comment by yuta-hitomi** [comment]
I interpreted `no_stocks` as number of stocks and defined `no_stocks` as the number of stocks included in the train/valid/test price.

Thanks.

**Comment by arnavw96** [comment]
Hi @yuta-hitomi, your interpretation is correct -- `no_stocks` represent the number of stocks to be considered for the train/val/test process, and needs to be specified for each dataset.
